import assert from "node:assert/strict";
import test, { afterEach, beforeEach } from "node:test";

import { GET, POST } from "../api/personalize-image.js";

const ENV_KEYS = [
  "AI_GATEWAY_API_KEY",
  "AI_GATEWAY_IMAGE_MODEL",
  "OPENAI_API_KEY",
  "OPENAI_IMAGE_MODEL",
  "PERSONALIZATION_ENABLED",
  "VERCEL_OIDC_TOKEN",
];
const originalEnvironment = Object.fromEntries(ENV_KEYS.map(key => [key, process.env[key]]));
const originalFetch = globalThis.fetch;

beforeEach(() => {
  for (const key of ENV_KEYS) delete process.env[key];
});

afterEach(() => {
  globalThis.fetch = originalFetch;
  for (const key of ENV_KEYS) {
    if (originalEnvironment[key] === undefined) delete process.env[key];
    else process.env[key] = originalEnvironment[key];
  }
});

function imageRequest(ip = "198.51.100.10", origin = "https://www.redscore.de") {
  const form = new FormData();
  const bytes = Uint8Array.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
  form.append("image", new File([bytes], "reference.png", { type: "image/png" }));
  form.append("scenario", "dashboard");
  form.append("household", JSON.stringify({ adults: 2, children: 1, dogs: 1 }));
  return new Request("https://www.redscore.de/api/personalize-image", {
    method: "POST",
    headers: { origin, "x-vercel-forwarded-for": ip },
    body: form,
  });
}

test("Vercel OIDC enables the project-scoped gateway automatically", async () => {
  process.env.VERCEL_OIDC_TOKEN = "test-oidc-token";
  const response = await GET();
  const payload = await response.json();

  assert.equal(payload.available, true);
  assert.equal(payload.provider, "vercel-ai-gateway");
});

test("a direct OpenAI key remains disabled without an explicit feature flag", async () => {
  process.env.OPENAI_API_KEY = "test-direct-token";
  const response = await GET();
  const payload = await response.json();

  assert.equal(payload.available, false);
  assert.equal(payload.provider, null);
});

test("the gateway receives the reference image and returns the generated bytes", async () => {
  process.env.VERCEL_OIDC_TOKEN = "test-oidc-token";
  globalThis.fetch = async (url, options) => {
    assert.equal(url, "https://ai-gateway.vercel.sh/v1/images/edits");
    assert.equal(options.headers.authorization, "Bearer test-oidc-token");
    assert.equal(options.body.get("model"), "openai/gpt-image-2");
    assert.equal(options.body.get("scenario"), null);
    assert.equal(options.body.get("image").type, "image/png");
    return Response.json({ data: [{ b64_json: Buffer.from("generated-image").toString("base64") }] });
  };

  const response = await POST(imageRequest("198.51.100.11"));
  assert.equal(response.status, 200);
  assert.equal(response.headers.get("content-type"), "image/webp");
  assert.equal(Buffer.from(await response.arrayBuffer()).toString(), "generated-image");
});

test("cross-origin uploads are rejected before an upstream request", async () => {
  process.env.VERCEL_OIDC_TOKEN = "test-oidc-token";
  globalThis.fetch = async () => assert.fail("upstream fetch must not run");

  const response = await POST(imageRequest("198.51.100.12", "https://example.org"));
  assert.equal(response.status, 403);
});

test("the best-effort server limit blocks the ninth hourly image request", async () => {
  process.env.VERCEL_OIDC_TOKEN = "test-oidc-token";
  let upstreamCalls = 0;
  globalThis.fetch = async () => {
    upstreamCalls += 1;
    return Response.json({ data: [{ b64_json: Buffer.from("generated-image").toString("base64") }] });
  };

  const responses = [];
  for (let index = 0; index < 9; index += 1) {
    responses.push(await POST(imageRequest("198.51.100.13")));
  }

  assert.equal(upstreamCalls, 8);
  assert.equal(responses.at(-1).status, 429);
  assert.ok(Number(responses.at(-1).headers.get("retry-after")) > 0);
});
